CREATE DATABASE IF NOT EXISTS mastering_go CHARACTER SET utf8mb4;

-- todosvr.models.Task
CREATE TABLE IF NOT EXISTS tasks (
	id BIGINT NOT NULL AUTO_INCREMENT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	title VARCHAR(4096) NOT NULL,
	subtitle VARCHAR(1024),
    done BOOL DEFAULT FALSE,
	PRIMARY KEY (id)
);
